// aboutText.ts

export const aboutText: string = `
Makerbox Lao is a collaborative work space for making, learning, exploring and sharing that uses high tech to no tech tools for kids, adults, and entrepreneurs.
Groups and individuals can come together in one place to share their ideas, produce their concepts, work with marketing, legal and sales professionals to understand more clearly needs and ways of developing products and solutions in line with consumer demands.

Support, mentorship, consultation and training will be available from industry experts, educational materials and university educators.

Materials for the maker space and coworking areas will be provided at different levels

Basic supplies for those people who want to play around with science and engineering to see how basic things work.

For students who want to research what areas of science or technology they might want to pursue when they think of applying for university.

Proof of concept level materials support – at this level, individuals or groups may present an idea that they wish to develop and create a prototype. For this level of materials support the group or individual will have to pitch their idea to a selection committee which will review the validity of the project and the potential uses and aftermarket.

Production support – at this level financial and material support will be provided and/or sought to bring a proven product concept to production and eventually to the market. AT this level, funding will be sought to ensure the project/product/service can be fully realized and brought to market.

The Makerbox Lao is funded by several organizations, will run as a not-for-profit entity, with the ultimate goal of being self-sustaining when ideas generated by participants in Makerbox Lao are launched into the market. We expect this may require up to five years, but if you wish to help us speed up the process, come talk to us.
`;
